export const IMAGES_PREVIEW_LOADING: string = 'IMAGES_PREVIEW_LOADING';
export const IMAGES_PREVIEW_SUCCESS: string = 'IMAGES_PREVIEW_SUCCESS';
export const IMAGES_PREVIEW_FAIL: string = 'IMAGES_PREVIEW_FAIL';
export const IMAGE_DELETE: string = 'IMAGE_DELETE';
export const IMAGES_ADD_TO_FAVORITE: string = 'IMAGES_ADD_TO_FAVORITE';
export const IMAGES_REMOVE_FROM_FAVORITE: string =
  'IMAGES_REMOVE_FROM_FAVORITE';
